name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'src/SmartFamily.Gedcom.Console/**'
    - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'src/SmartFamily.Gedcom.Console/**'
    - 'README.md'

jobs:
  build:
    name: Build Package
    runs-on: windows-latest
    strategy:
      matrix:
        ChannelName:
          - Release
    
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      BuildConfiguration: Release
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GitHubReleaseUrl: https://github.com/amwiens/SmartFamily.Gedcom/releases/download/

    steps:
    - uses: actions/checkout@v2
    
    - name: Use .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Nerdbank.GitVersioning
      uses: dotnet/nbgv@v0.4.0
      with:
        setCommonVars: true
        
    - run: echo "BuildNumber - ${{ env.GitBuildVersionSimple }}"
    
    - name: Create Directory for Channel
      run: mkdir ${{ github.workspace }}\${{ matrix.ChannelName }}
      shell: powershell
      
    - name: Add Version File to Artifact
      run: |
        
        
        New-Item -Path ${{ github.workspace }}\${{ matrix.ChannelName }} -Name "version.txt" -ItemType "file" -Value "${{ env.GitBuildVersionSimple }}"
      shell: powershell
    
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore

    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Release --no-restore

    - name: Test
      working-directory: ./src
      run: dotnet test --no-build --verbosity normal
